import 'package:functional_widget_annotation/functional_widget_annotation.dart';

import 'flutter.dart';

part 'edge.g.dart';

/// Tests where the code is technically not valid, but the generator still needs
/// to run correctly.
///
/// A typical scenario is where a function uses a class generated by another class

@widget
// ignore: undefined_class
Widget undefinedType({Undefined foo}) => Container();
